.travis.yml
tests/run.py

Move lcov to cover all tests not just those run by run.py

Travis lcov

---

src/main/cpp/include/loader/tiledb_loader_file_base.h

see https://github.com/broadinstitute/gatk/issues/5568

Silence buffer resize logging (Simple PR)

---

src/main/cpp/src/config/genomicsdb_config_base.cc
src/main/cpp/src/config/json_config.cc
src/main/cpp/src/config/variant_query_config.cc
src/main/java/org/genomicsdb/reader/GenomicsDBFeatureReader.java
src/resources/genomicsdb_export_config.proto
tests/golden_outputs/java_t0_1_vcf_at_0
tests/golden_outputs/t0_1_vcf_at_0
tests/run.py

https://github.com/broadinstitute/gatk/issues/5570
Added field in query JSON/Protobuf to specify list of lists of sample names to include in query. The list of lists structure matches the structure of _query_row_ranges_ in the original JSON spec.
Rest of the changes are to support this feature.
CI test for feature.

For gatk-5570

---

src/main/cpp/include/genomicsdb/variant_storage_manager.h
src/main/cpp/src/genomicsdb/variant_storage_manager.cc
src/main/java/org/genomicsdb/GenomicsDBUtils.java
src/main/java/org/genomicsdb/GenomicsDBUtilsJni.java
src/main/java/org/genomicsdb/importer/GenomicsDBImporter.java
src/main/java/org/genomicsdb/reader/GenomicsDBFeatureReader.java
src/main/jni/include/genomicsdb_GenomicsDBUtils.h
src/main/jni/src/genomicsdb_GenomicsDBUtils.cc
src/test/java/org/genomicsdb/importer/GenomicsDBImporterSpec.java

Fix/change to automatically get lbrowidx from genomics metadata for incremental update (instead of requiring the user to set it)

Incremental import fixes

---

example/java/TestGenomicsDBDataSourceV2.java
example/java/TestGenomicsDBSparkHDFS.java
src/main/java/org/genomicsdb/spark/GenomicsDBDataSourceReader.java
src/main/java/org/genomicsdb/spark/GenomicsDBInput.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputFormat.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputInterface.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputPartition.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputPartitionReader.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputSplit.java
src/test/java/org/genomicsdb/GenomicsDBTestUtils.java
src/test/java/org/genomicsdb/spark/GenomicsDBInputFormatTest.java
tests/run_spark_hdfs.py

Smarter way to group together query ranges.

Glom snps when querying through spark

---

example/java/TestGenomicsDBImporterWithMergedVCFHeader.java
src/main/cpp/src/vcf/genomicsdb_bcf_generator.cc
src/main/java/org/genomicsdb/importer/GenomicsDBImporter.java
src/main/java/org/genomicsdb/importer/MultiChromosomeIterator.java
src/main/java/org/genomicsdb/reader/GenomicsDBFeatureIterator.java

Some changes to deal with issues that cropped up with GATK testing. I will add an issue to add some tests so that we catch these in our tests as well. For now, just want to get this out so that we can get a PR up for GATK.

fix for issues found through GATK testing

---

cmake/Modules/Findhtslib.cmake

This brings in latest changes resulting from these PRs - https://github.com/GenomicsDB/htslib/pull/7 and https://github.com/OmicsDataAutomation/TileDB/pull/69.

Move to newer dependencies

---

src/test/cpp/CMakeLists.txt
src/test/cpp/include/test_base.h
src/test/cpp/src/test_columnar_gvcf_iterator.cc
tools/src/gt_mpi_gather.cc

Added one basic test for sanity testing the columnar gvcf iterator.

Unit test for the columnar gvcf iterator

---

src/main/cpp/include/genomicsdb/genomicsdb_iterators.h
src/test/cpp/include/test_common.h
src/test/cpp/src/ctest_main.cc
src/test/cpp/src/test_columnar_gvcf_iterator.cc
src/test/cpp/src/test_pb.cc
tests/run.py

* Uses golden outputs from previously running VCF tests
* Subset of fields checked - more will be added as functionality is added
* Invoked from within run.py
* Minor cleanup

"Unit" tests for columnar GVCF iterator

---

src/main/cpp/include/genomicsdb/genomicsdb_columnar_field.h
src/main/cpp/include/genomicsdb/genomicsdb_iterators.h
src/main/cpp/include/genomicsdb/variant_cell.h
src/main/cpp/src/genomicsdb/genomicsdb_columnar_field.cc
src/main/cpp/src/genomicsdb/genomicsdb_iterators.cc
src/test/cpp/src/test_columnar_gvcf_iterator.cc

No feature changes - see commit message for explanation

Renamed a bunch of functions and variables for consistency

---

tools/src/gt_mpi_gather.cc

Message for gt_mpi_gather --help updated as per wiki docs.

fix gt_mpi_gather --help

---

.github/workflows/basic.yml
pom.xml

minor: bring back java11 CI tests

---

scripts/prereqs/install_prereqs.sh

Minor : Download maven from downloads.apache.org in the scripts 

---

tests/test_tools.sh

Associative arrays are not supported in bash 3.2, so reverting to calling `run_command` explicitly for compression type/level tests. GitHub Actions actually had failed for MacOS builds for #166, but for some reason did not error out the build.
Also, refactored `create_template_loader_json` to optionally accept compression types and levels

Fix script to run on Mac that is still on bash version 3.2 as opposed to 4.x on Linux

---

src/main/cpp/src/config/json_config.cc
src/main/cpp/src/vcf/vcf_adapter.cc
tests/test_tools.sh
tools/src/gt_mpi_gather.cc

Reference files are required only when producing gcvf files, so leave the check to the tools(gt_mpi_gather or gatk SelectVariants). Cleaned up error messages during `ReferenceGenome::initialize` for issues with the reference genome file. Added gt_mpi_gather checks in test_tools.sh for checking the reference_genome configuration.
The source in json_config.cc has a mixture of tabs and spaces. Replaced all tabs with spaces to make it easier to read from both emacs and vi, there are no other changes.

Check reference genome files in configuration only when required while producing gvcf files

---

src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/config/genomicsdb_config_base.cc
src/main/cpp/src/genomicsdb/genomicsdb_iterators.cc
src/main/cpp/src/genomicsdb/query_variants.cc
src/main/cpp/src/loader/load_operators.cc
src/main/cpp/src/query_operations/broad_combined_gvcf.cc
src/main/cpp/src/query_operations/variant_operations.cc
src/main/cpp/src/utils/command_line.cc
src/main/cpp/src/utils/vid_mapper_pb.cc
src/main/cpp/src/vcf/vcf2binary.cc

Prints to file e.g. csv were not changed so should be fine.

Changed various user facing prints to logger

---

CMakeLists.txt
scripts/README.md
scripts/prereqs/install_prereqs.sh
tests/test_tools.sh
tools/EnvironmentVariables.md
tools/src/vcf2genomicsdb_init.cc

This PR picks up the latest bookkeeping changes. Also made minor changes to scripts mainly for MacOS and added progress monitoring to vcf2genomicsdb_init while merging headers to create template headers.

Pick up bookkeeping changes and added progress monitoring to vcf2genomicsdb_init while merging 

---

src/main/cpp/src/genomicsdb/variant_storage_manager.cc
tests/run.py
tests/run_spark_hdfs.py
tests/test_tools.sh

A little refinement here - VariantStorageManager should check for existence of the workspace first. Otherwise, initialize_workspace creates one.

VariantStorageManager should have an existing workspace to be functional, otherwise throw a VariantStorageManagerException

---

.github/workflows/release_jar.yml
.github/workflows/release_publish.yml

Updates to add sources, javadoc and sign the artifacts

Release flow updates

---

.github/workflows/release_publish.yml

Really minor but...I had to manually log onto nexus and close/release the repository for the latest release. Hopefully, this change will fix that for next time around 🤞

Try to automate last little bit for mvn central publish

---

cmake/Modules/CheckAndSetStdCXX2011Flag.cmake
example/java/TestGenomicsDB.java
example/java/TestGenomicsDBSource.java
pom.xml
src/main/java/org/genomicsdb/importer/GenomicsDBImporter.java
src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java
src/main/java/org/genomicsdb/importer/extensions/JsonFileExtensions.java
src/main/java/org/genomicsdb/spark/api/GenomicsDBSparkBindings.java

This fixes #228 and #229.  I am still thinking about how to handle the fmt issue (#230) as we mostly just use the header from spdlog. And @mlathara, I will leave #231 to you. One of the dependabot's PRs also got pulled into this branch.

Some fixes for Debian

---

CMakeLists.txt
scripts/prereqs/system/install_macos_prereqs.sh

Tried onboarding a new user on a Mac and these scripts needed tweaking.

Fixes for Mac and new cmake option for usecases that do not need testing

---

docs/apis.rst
docs/cli-tools.rst
docs/conf.py
docs/examples/python.ipynb
docs/requirements.txt

Update docs notebook to use protobuf. And some changes that @Santhosh-K-M mentioned while reading the docs...
Edit: it is linked out from the checks below but just for completeness here is the link to what the docs look like after these changes: https://genomicsdb--269.org.readthedocs.build/en/269/

Update python notebook for docs

---

.github/workflows/release_test.yml

Use GENOMICSDB_TAG to test with a version compatible GenomicsDB for smoke testing with GenomicsDB/TestGenomicsDBJar

Use GENOMICSDB_TAG to test with a version compatible GenomicsDB for smoke testing with TestGenomicsDBJar

---

.github/scripts/install_hadoop.sh
.github/workflows/basic.yml
.github/workflows/codeql.yml
.github/workflows/docker.yml
.github/workflows/release.yml
.github/workflows/release_publish.yml
.github/workflows/release_test.yml
CMakeLists.txt
Dockerfile.release
Dockerfile.release_prereqs
pom.xml
scripts/prereqs/install_prereqs.sh
scripts/prereqs/system/install_centos_prereqs.sh
scripts/prereqs/system/install_macos_prereqs.sh
scripts/prereqs/system/install_ubuntu_prereqs.sh
tests/common.py

Migrated to java 17, removed java 8 support and kept java 11 support. Updated dependencies, workflows and scripts according to java 17 change.

java 17 support

---

.github/workflows/release_publish.yml
CMakeLists.txt
scripts/prereqs/install_prereqs.sh

- Added back allinone jar for publishing as it does help in testing from [TestGenomicsDBJar](https://github.com/GenomicsDB/TestGenomicsDBJar) for example
- Tweaked `mvn nexus-staging` to allow for releasing automatically.

Finalize release sonatype flow

---

Dockerfile

Minor Dockerfile fix

---

src/main/cpp/src/vcf/hfile_genomicsdb.c

Adds azb support for htslib operations.

Htslib azb support

---

src/main/cpp/src/vcf/htslib_fs_adapter.cc
src/main/cpp/src/vcf/vcf2binary.cc
src/main/java/org/genomicsdb/importer/GenomicsDBImporter.java
src/main/jni/src/genomicsdb_GenomicsDBImporter.cc
src/test/java/org/genomicsdb/importer/GenomicsDBImporterSpec.java
tests/test_hfile_plugin.sh

This needs additional junits which I am still working on. But, @mlathara, please feel free to review the code. Thanks.

Catch JNI importer exceptions and propagate them as java IOExceptions
