GenomicsDB/GenomicsDB

src/main/java/org/genomicsdb/importer/GenomicsDBImporter.java

An example usecase is to allow changes for allele specific annotations without hardcoding them in genomicsdb

vid mapping update from genomicsdbimporter

---

.gitmodules
src/test/cpp/include/test_mapping_data_loader.h
src/test/cpp/src/CMakeLists.txt
src/test/cpp/src/ctest_main.cc
src/test/cpp/src/main_testall.cc
src/test/cpp/src/test_mapping_data_loader.cc
src/test/cpp/src/test_multid_vector.cc
src/test/cpp/src/test_non_diploid_mapper.cc

Catch2 is
- Header only   
-  No need for fixtures   
-  Really nice expression support for matchers.

Move GenomicsDB C/C++ tests to use Catch2 instead of Google Test

---

.travis.yml
.travis/scripts/install_osx_dependencies.sh

We do not need guest anymore as we have moved to Catch2.

Remove installing gtest for travis tests

---

.gitignore
.travis.yml
CMakeLists.txt
tests/common.py
tests/run.py
tests/run_spark_hdfs.py

Refactored common jacoco parts out of run.py and run_spark_hdfs.py into common.py
Added support to pass an optional build-type argument to the CI scripts.

Support jacoco for the new allinone GenomicsDB jars

---

src/main/java/org/genomicsdb/spark/GenomicsDBConfiguration.java
src/main/java/org/genomicsdb/spark/GenomicsDBDataSourceReader.java
src/main/java/org/genomicsdb/spark/GenomicsDBInput.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputFormat.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputPartition.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputPartitionReader.java
src/main/java/org/genomicsdb/spark/GenomicsDBJavaSparkFactory.java

I had to resort to SuppressWarning annotation for a few of these. In a couple of instances I'm trying to reuse some code that breaks up spark work into chunks for the workers. The interfaces/classes used for the RDD path vs the dataframe path don't share any common superclasses...so I couldn't figure out a way to get rid of the unchecked cast for those.

minor cleanup for warnings

---

src/main/java/org/genomicsdb/reader/GenomicsDBFeatureIterator.java
src/main/java/org/genomicsdb/reader/GenomicsDBFeatureReader.java
src/main/java/org/genomicsdb/reader/GenomicsDBQueryStream.java
src/main/jni/include/genomicsdb_GenomicsDBQueryStream.h
src/main/jni/src/genomicsdb_GenomicsDBQueryStream.cc

Remove catch(...) in jniGenomicsDBInit as that was masking the C/C++ exceptions thrown. 
The FeatureReader interface has query/iterator/close all throw IOExceptions, so
- Matched GenomicsDBFeatureReader implementation of FeatureReader to throw IOExceptions. 
- Got GenomicsDBStream constructors and jniGenomicsDBInit to throw IOExceptions as well.
This allowed us to see the IOExceptions propagated into the gatk layers where the IOException was handled properly. e.g
```
org.broadinstitute.hellbender.exceptions.GATKException: Error querying gendb:///tmp/genomicsDBWorkspace5332118045648407634/workspace over interval 20:1-63025520
... Stack Trace ...
Caused by: java.io.IOException: GenomicsDB JNI Error: Broad combine GVCFs exception : Unknown contig for position 2728661124
... GenomicsDB Stack …
```

Allow for IOExceptions to propogate into GenomicsDBFeatureReader

---

CMakeLists.txt
cmake/Modules/FindProtobufWrapper.cmake
src/main/cpp/include/query_operations/broad_combined_gvcf.h
src/main/cpp/include/query_operations/variant_operations.h
src/main/cpp/include/utils/vid_mapper.h
src/main/cpp/src/config/pb_config.cc
src/main/cpp/src/genomicsdb/query_variants.cc
src/main/cpp/src/genomicsdb/variant_field_handler.cc
src/main/cpp/src/query_operations/broad_combined_gvcf.cc
src/main/cpp/src/query_operations/variant_operations.cc
src/main/cpp/src/utils/vid_mapper.cc
src/main/cpp/src/utils/vid_mapper_pb.cc
src/main/java/org/genomicsdb/importer/extensions/VidMapExtensions.java
src/resources/genomicsdb_vid_mapping.proto
src/test/java/org/genomicsdb/importer/GenomicsDBImporterSpec.java

* Reduce memory usage when dealing with allele specific annotation fields: this caused the most code changes. If there is an INFO field such that:
* Its value is dependent on the order of the alleles and
* Its combine operation is associative and commutative (just sum in this commit)
, then this PR will cause this fields data to be remapped and the sum to be computed incrementally sample by sample. Earlier, the field would be remapped for all samples first and then the sum computed -- more memory than necessary would be used.
* Fix for https://github.com/broadinstitute/gatk/issues/6158

Reduce memory usage

---

.travis.yml
example/java/TestGenomicsDBDataSourceV2.java
example/java/TestGenomicsDBSparkHDFS.java
pom.xml
src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java
src/main/java/org/genomicsdb/reader/GenomicsDBFeatureIterator.java
src/main/java/org/genomicsdb/reader/GenomicsDBQueryStream.java
src/main/java/org/genomicsdb/spark/GenomicsDBConfiguration.java
src/main/java/org/genomicsdb/spark/GenomicsDBInput.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputFormat.java
tests/common.py

We were passing in protobuf as json string in for spark. It turns out that Google's python protobuf sends in int64 as string (for reasons specified in many places, for instance [here)](https://github.com/protocolbuffers/protobuf/issues/2679)
So this moves us to expect protobuf bytestream instead. Since we use hadoop configuration to pass the config, it gets encoded as a base64 string on the sender side - so the receiver decodes that first before ingesting the protobuf object.
Also, a few annoying travis Mac OS changes.

Protobuf as bytearray for spark conf

---

src/main/java/org/genomicsdb/spark/GenomicsDBInput.java
src/test/java/org/genomicsdb/GenomicsDBTestUtils.java
src/test/java/org/genomicsdb/spark/GenomicsDBInputFormatTest.java

Found a bug with the spark partitioning that kicks in when we try to create queries that are larger than arrays. Added a test as well

bug fix and test for spark partitioning issue

---

pom.xml
src/main/cpp/include/api/genomicsdb.h
src/main/cpp/include/config/genomicsdb_config_base.h
src/main/cpp/include/config/variant_query_config.h
src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/config/variant_query_config.cc
src/main/java/org/genomicsdb/reader/GenomicsDBQuery.java
src/main/jni/include/genomicsdb_GenomicsDBQuery.h
src/main/jni/src/genomicsdb_GenomicsDBQuery.cc
src/test/cpp/CMakeLists.txt
src/test/cpp/include/test_base.h
src/test/cpp/src/test_config.cc
src/test/cpp/src/test_genomicsdb_api.cc
src/test/java/org/genomicsdb/reader/GenomicsDBQueryTest.java

Allow for JSON/JSON strings/Protobuf binary strings to be passed as export configuration to GenomicsDB API

Refine GenomicsDB API with support for Protobuf and JSON strings

---

.gitmodules
CMakeLists.txt
cmake/Modules/FindSpdlog.cmake
cmake/Modules/FindTileDB.cmake
cmake/Modules/Findhtslib.cmake
src/main/CMakeLists.txt
src/main/cpp/include/loader/tiledb_loader_file_base.h
src/main/cpp/include/utils/logger.h
src/main/cpp/src/query_operations/broad_combined_gvcf.cc
src/main/cpp/src/utils/known_field_info.cc
src/main/cpp/src/utils/logger.cc
src/main/cpp/src/utils/vid_mapper.cc
src/main/cpp/src/vcf/vcf2binary.cc
src/main/cpp/src/vcf/vcf_adapter.cc
src/test/cpp/CMakeLists.txt
src/test/cpp/src/test_logger.cc

Evaluated Spdlog against glog, Spdlog seems to be pretty good and header only, so went with that. Spdlog is brought in as an external submodule like RapidJson. Note that there are cmake changes to automatically run `git submodule update` if any of the submodules are not found.
We can extend the Logger functionality later for tracing and make it configurable with multiple sinks, but the basic functionality is in. What I particularly like is the [format functionality](http://fmtlib.net/latest/) similar to how python formatting works. 
- Exposed a global Logger instance, sufficient for most uses.
- Logger can be used with `fmt` or directly with std::string. When used directly with std::string there is no formatting of any kind. The default formatting is similar to the default log4j, but with …

Initial support to use spdlog for C/C++ logging

---

src/main/CMakeLists.txt
src/main/cpp/include/api/genomicsdb.h
src/main/cpp/include/utils/gt_common.h
src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/api/genomicsdb_field.cc

This PR addresses some of the comments from #86. And also fixes the issue with genomicsdb_field_t::to_string() not handling missing GT fields correctly.
- Remove some duplicated defines and move other commonly used ones to gt_common.h
- Refactor genomicsdb.h by moving the handling of individual genomic fields to genomicsdb_field.cc so there is no direct dependency on gt_common.h from genomicsdb.h.
- What's implemented in this PR is the specialized handling for GT and ALT when `genomicsdb_field_t::to_string()` is invoked.
- Looking at #59 to handle `FILTER` and `ID`. @kgururaj, @mlathara let me know if any other fields need special handling.
Will address making `genomicsdb_field_type_t` a pointer to `FieldInfo` in another PR. There were some issues(mainly assertions getting thrown) with …

Cleanup and support GT missing fields in api

---

src/main/cpp/src/vcf/vcf2binary.cc

For the case when the index file cannot be open due to an actual errno(e.g. running out of file handles), htslib ignores the errno and just puts out the error message "could not load index". We now add errno to the htslib error message when bcf_sr_add_reader is invoked - see Issue #1.  Also, tried to make a pass at other htslib api used in GenomicsDB, they seem to handle the errno fine, that is they pass it back in the error message to the client.

Add errno to error message when bcf_sr_add_reader is invoked as htslib errmsg is sometimes insufficient. 

---

CMakeLists.txt

Change minimum supported cmake version to 3.4, same as support for BUILD_DISTRIBUTABLE_LIBRARY. This is because of incompatibilities introduced in the newer cmake 3 versions with cmake2 . For example, cmake3 requires `find_package(Protobuf)` instead of `include(FindProtobuf)` in FindProtobufWrapper.cmake. See [GenomicsDB-Install](https://github.com/nalinigans/GenomicsDB-Install/commit/894441b6b0cec107131879c73d14bf6751ff31b3) changes that now uses `cmake3` for building.
Also, move to new htslib to pick up changes with GCS authentication.

Change minimum supported cmake version to 3.4

---

codecov.yml
src/main/cpp/include/genomicsdb/genomicsdb_iterators.h
src/main/cpp/include/genomicsdb/variant_storage_manager.h
src/main/cpp/src/genomicsdb/genomicsdb_iterators.cc
src/main/cpp/src/genomicsdb/variant_storage_manager.cc
src/main/cpp/src/query_operations/broad_combined_gvcf.cc
src/main/cpp/src/vcf/vcf2binary.cc
src/main/cpp/src/vcf/vcf_adapter.cc

Checking for `bcf_hdr_sync()` return values to silence clang, just logging the errors for now. Should we throw an exception here?

Cleanup clang warnings and move to new version of dependencies

---

.travis.yml

Travis/Trusty seems to have a preinstalled protobuf that broke the builds. For now, changed the script to use the 3.0.2 version from [here](https://github.com/GenomicsDB/GenomicsDB/releases/download/v1.0.0/protobuf-3.0.2-trusty.tar.gz), but we should investigate building with the installed protobuf later.

Explicitly use protobuf 3.0.2 to work around travis using a preinstalled protobuf

---

src/main/cpp/include/utils/logger.h
src/main/jni/src/genomicsdb_GenomicsDBImporter.cc
src/test/cpp/src/test_logger.cc

* Change `logger.fatal` to be a template for the std::exception argument as the polymorphic context is lost in subsequent re-throws of std::exception.
* Introduced env variable `GENOMICSDB_PRINT_STACKTRACE` to print a stack trace especially from JNI or other language bindings where the exceptions are caught and propagated into the Java layer as graceful Java Exceptions.
* Also removed code catching ParseFromArray exceptions from [here]( https://github.com/GenomicsDB/GenomicsDB/blob/e701905e0bb54765e22119a71038c0e64c85b9c3/src/main/jni/src/genomicsdb_GenomicsDBImporter.cc#L272) as it suffers from the same polymorphic issue as logger.fatal() and it does not throw exceptions, just returned a Boolean status. These exceptions at some point will have to be rethrown as java exceptions for a more …

Fix issues with propagating polymorphic std::exception code

---

src/main/cpp/include/config/variant_query_config.h
src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/config/variant_query_config.cc
src/main/cpp/src/vcf/genomicsdb_bcf_generator.cc
src/test/cpp/src/test_genomicsdb_api.cc

Note that while adding a unit test for GenomicsDB api with protobuf bytes, `read_from_PB...` has been added to VariantQueryConfig for the config to get validated similar to `read_from_file` and `read_from_JSON_string`.

Add test for GenomicsDB api protobuf bytes support

---

.travis.yml
src/main/java/org/genomicsdb/spark/api/GenomicsDBQueryInputFormat.java

Cleanup createRecordReader functionality in spark bindings to query api and add a basic build for MacOS in the travis build matrix.

Refactor createRecordReader functionality in spark bindings to query api

---

CMakeLists.txt
src/main/cpp/include/genomicsdb/genomicsdb_iterators.h
src/main/cpp/include/utils/headers.h
src/main/cpp/src/genomicsdb/genomicsdb_iterators.cc

Minor cleanup.
Thought that it is better for the GenomicsDB Iterator Methods to use the field_index as the first parameter to fit with the Columnar theme. It made the reading of the code flow better for me. But, if any of you feel it is better to leave as is, that is fine by me too.

Minor cleanup and rearrange arguments to the GenomicsDB Iterator

---

.travis.yml
.travis/resources/hadoop/hadoop-env.sh
.travis/scripts/install_hadoop.sh
.travis/scripts/install_spark.sh

Hadoop 2.7.7 is no longer generally available, so move to 2.9.2 for now as a first stop. We will eventually have to move to Hadoop 3.x, but need to be sure that spark operates fine first.

Move to Hadoop 2.9.2 for Travis tests

---

.github/workflows/basic.yml
scripts/prereqs/install_prereqs.sh
scripts/prereqs/system/install_centos_prereqs.sh
scripts/prereqs/system/install_ubuntu_prereqs.sh

This implements the basic build-test workflow for Ubuntu. What is left to be on par with travis are the following -
1. Install bcftools for checking generated vcfs with run.py
2. MacOS support
Also, we should refactor the `ci-job` currently implemented into 3 jobs
1. setup (will install system and python prereqs and cache them for further use, not sure on caching .m2 without serializing basic and spark jobs)
2. basic
3. spark
Both `basic` and `spark` jobs can run in parallel, but they will be dependent on `setup`. See [Github Docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds) for expressing job dependencies.

GitHub Actions to build and test GenomicsDB

---

CMakeLists.txt
pom.xml

Basic updates required to publish jar to maven central. Includes:
* update GenomicsDB version to 1.4.0, incrementing for Spark3 changes
* gpg-plugin version change to 1.6
* ability to pass gpg passphrase through cmake 
Ready for review.

Maven deploy central updates

---

.github/workflows/basic.yml
.github/workflows/spark2.yml
README.md
src/main/cpp/include/vcf/hfile_genomicsdb.h
src/main/cpp/src/vcf/hfile_genomicsdb.c
src/main/cpp/src/vcf/htslib_fs_adapter.cc
src/test/cpp/src/test_htslib_plugin.cc

Moving to the latest TileDB introduced one api change with `file_size()` returning a `ssize_t` as compared to `size_t` before. Got the genomicsdb htslib plugin to react to this change and also cleaned up the initialization phase to factor in file modes and checking if the file exists to remove unnecessary TileDB warnings.
Added badges and cleaned up the basic workflow a little. 
One question, should we run MacOS tests only for PRs as the junits/jacoco are taking an inordinate amount of time? We could also just run the C/C++ tests for MacOS pushes and the entire gamut for PRs. Thoughts?

Move to using latest dependencies and replace travis with GitHub action badges

---

src/main/cpp/include/api/genomicsdb.h
src/main/cpp/include/config/genomicsdb_config_base.h
src/main/cpp/src/api/genomicsdb.cc
src/resources/genomicsdb_export_config.proto
src/test/cpp/src/test_genomicsdb_api.cc
src/test/java/org/genomicsdb/reader/GenomicsDBQueryTest.java

These changes add the vcf annotation service to GenomicsDB. 
* I modified the signature of a few functions in genomicsdb.h. Seems like that may not be ok. 
* I didn't end up implementing the map we discussed for storing/cacheing annotation values. 
* When I view the VariantCall.genomicFields map from within GenomicsDB the annotation values are there, but when I look at the map in Java the annotation values aren't there. Could this be because the string values are out of scope and this will be resolved by creating the map for storing string values?

Annotation service created using HTSLib

---

.github/workflows/basic.yml
.github/workflows/spark2.yml
CMakeLists.txt
cmake/Modules/Findhtslib.cmake
src/main/cpp/src/vcf/hfile_genomicsdb.c

1. Move to TileDB version using native client support for aws and gcs to allow for native handling of s3 and gs urls instead of piggybacking on HDFS/JNI.
2. Direct GenomicsDB support to handle `s3://`and `gs://` urls for samples instead of htslib. This allows GenomicsDB to use the standard aws/gcs sdk paradigms via TileDB to help with authentication, retries with exponential backoff, configuring credentials, endpoints, profiles, etc.
3. Github Action changes to help with building `aws` and `gcs` sdks as a prerequisite and caching them for future builds. Also, moved spark2 compatibility builds for only `master` and `develop` branches on push and pull requests.

Better GenomicsDB s3 and gs url support

---

.github/workflows/basic.yml
.github/workflows/spark2.yml
CMakeLists.txt
cmake/Modules/Findhtslib.cmake
scripts/prereqs/install_prereqs.sh
src/main/cpp/src/genomicsdb/variant_storage_manager.cc
tests/run.py

After including GCS, AWS and Azure SDKs for cloud support in TileDB, remove -lcurl while building htslib as GenomicsDB relies on hts plugins and the sdks to support all gs://, s3:// and az:// paths.
Also, clean up appending cloud file paths by first checking whether the path has a trailing slash as `/` can be an object(folder or file) by itself under any folder.

Fix htslib cmake Module to not have lib curl dependencies and factor in trailing slash while appending file paths

---

CMakeLists.txt
cmake/Modules/Findhtslib.cmake

- Fix broken htslib build with MacOS (11.2) Big Sur. Big Sur now comes with framework libraries preloaded and the actual library is only metadata. The workaround is to include  `-L /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib` explicitly which `CMAKE_MODULE_LINKER_FLAGS` already does.
- Move to `MACOSX_DEPLOYMENT_TARGET to 10.13` because of gcs sdk dependency.
- React to autoconf 2.70 by invoking `autoconf -i` to generate missing auxiliary files (this breaks GitHub Actions 10.15 Catalina builds too)

Fix broken htslib build with macOS Big Sur

---

.github/workflows/basic.yml
CMakeLists.txt
cmake/Modules/FindProtobufWrapper.cmake
pom.xml
scripts/prereqs/install_prereqs.sh
src/resources/CMakeLists.txt

Move to protobuf 3.8.0. This features 
1. Building of protobuf from within GenomicsDB, once per version and is stored in `$HOME/protobuf-install/<Version>`, e.g. `/home/nalini/protobuf-install/3.8.0`. The protobuf version and url to the protobuf zips are cmake cache variables and can be overridden with cmake. Will also solve issues like that reported in #62.
2. Move the GitHub builds to `fail-fast=off`, so all builds get run even with build failures.
3. Turned off building Java 11 for now because of shaded protobuf package issues. [gatk builds ](https://travis-ci.com/github/broadinstitute/gatk/builds/226469302)with the published snapshot jar from this branch seem to be fine.

Move to protobuf 3.8.0 to match gatk's version and also for use with the genomicsdb tools

---

.github/scripts/install_hadoop.sh

Download Hadoop from the archives so we don't keep changing versions in the build when they are pulled off the main download sites.

Download hadoop from archive.apache.org

---

src/main/cpp/include/api/annotation_service.h
src/main/cpp/src/api/annotation_service.cc
src/resources/genomicsdb_export_config.proto
src/test/cpp/src/test_genomicsdb_api.cc

Based on [feedback in PR](https://github.com/GenomicsDB/GenomicsDB/pull/186#discussion_r740577566), the changes to m_annotation_buffer is now a std::vector<unit8_t> instead of std::vector\<std::string>. The buffer is sized to either 10K(default) or to what is specified in GenomicsDBExportConfiguration.

Address the annotation buffer issue for storing the annotation field values

---

.github/scripts/install_hadoop.sh
.github/workflows/basic.yml
CMakeLists.txt
pom.xml
scripts/prereqs/install_prereqs.sh
src/main/java/org/genomicsdb/importer/GenomicsDBImporter.java
src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java
src/main/java/org/genomicsdb/importer/extensions/JsonFileExtensions.java
src/test/java/org/genomicsdb/importer/GenomicsDBImporterSpec.java

This is a fix for broadinstitute/gatk#7598. We throw exceptions allowing for an abort/exit when any of the jsons or vcfheader template cannot be persisted for any reason e.g.
```
14:01:25.031 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/nalini/gatk/build/install/gatk/lib/gkl-0.8.8.jar!/com/intel/gkl/native/libgkl_compression.dylib
14:01:25.332 INFO  GenomicsDBImport - ------------------------------------------------------------
14:01:25.332 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.2.2.0-34-g964b5d7-SNAPSHOT
14:01:25.332 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
14:01:25.332 INFO  GenomicsDBImport - Executing as nalini@ng on Mac OS X v10.16 x86_64
14:01:25.333 INFO …
```

Fix for gatk issue #7598

---

CMakeLists.txt
cmake/Modules/FindGPerftools.cmake
cmake/Modules/Findlibcsv.cmake
src/main/cpp/src/loader/load_operators.cc
tools/src/gt_mpi_gather.cc
tools/src/vcf2genomicsdb.cc

1. Add support for running gperf/heap profiler with tools - `vcf2genomicsdb` and `gt_mpi_gather`. The generated profiles are named `\<toolname\>.gperf.heap` for heap profiler and `\<toolname\>.gperf.prof` for the default(cpu) profiler.
2. Pull in fix with book_keeping and cloud URLs.
3. Minor cleanup.

Add support for running gperf heap profiler from the tools.

---

CMakeLists.txt
src/main/cpp/include/genomicsdb/variant_storage_manager.h
src/main/cpp/include/loader/tiledb_loader.h
src/main/cpp/include/utils/genomicsdb_logger.h
src/main/cpp/src/genomicsdb/variant_storage_manager.cc
src/main/cpp/src/loader/tiledb_loader.cc
src/main/cpp/src/utils/genomicsdb_logger.cc
tests/test_tools.sh
tools/src/consolidate_genomicsdb_array.cc

Support buffer/batch sizes and enabling shared posixfs optimizations in the consolidate_genomicsdb_array tool and from the Java/C++ Importer via loader configuration.
Also, cleaned up logging to conform to log4j defaults and bumped up the release version to 1.4.4.snapshot in CMakeLists.txt.

Support buffer/batch sizes and enabling shared posixfs optimizations in the consolidate_genomicsdb_array tool and from the Importer

---

.github/workflows/basic.yml
CMakeLists.txt
pom.xml

- Move to `cmake version 3.17` for `SOURCE_SUBDIR` support used in finding locally built protobuf.
- Move to `protobuf version 3.19.4` to match gatk.

Move to cmake 3.17 and protobuf 3.19.4

---

CMakeLists.txt
cmake/Modules/FindTileDB.cmake

Something in the cmake newer versions has changed, we need to force `CMAKE_BUILD_TYPE` default to `Release` now. Otherwise the default is empty string, the [docs](https://cmake.org/cmake/help/v3.3/variable/CMAKE_BUILD_TYPE.html) when `CMAKE_BUILD_TYPE` is empty is not very clear, but it looks like it could be `Debug` which is what I am seeing. There is also `CMAKE_CONFIGURATION_TYPES` which `CMAKE_BUILD_TYPE` is part of, but I don't want to visit it that yet.
Also, force set TILEDB_VERBOSE to False, otherwise we see multiple error messages as GenomicsDB also logs tiledb_errmsg via spdlog.

Force CMAKE_BUILD_TYPE to Release and TILEDB_VERBOSE to False as they are cached cmake variables

---

src/main/CMakeLists.txt
src/main/cpp/include/api/genomicsdb.h
src/main/cpp/include/api/genomicsdb_plink.h
src/main/cpp/include/config/genomicsdb_config_base.h
src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/api/genomicsdb_field.cc
src/main/cpp/src/api/genomicsdb_plink.cc
src/main/java/org/genomicsdb/reader/GenomicsDBQuery.java
src/main/java/org/genomicsdb/spark/api/GenomicsDBQueryInputFormat.java
src/main/jni/include/genomicsdb_GenomicsDBQuery.h
src/main/jni/src/genomicsdb_GenomicsDBQuery.cc
src/test/cpp/src/test_bgen.cc
src/test/cpp/src/test_genomicsdb_api.cc
src/test/java/org/genomicsdb/reader/GenomicsDBQueryTest.java
tools/src/gt_mpi_gather.cc

1. Reference Genome is not required for normal queries and is moved out of the constructor into methods - `generate-vcf` when broad-type gvcf files have to be created from GenomicsDB. Also, support for vcf header templates to be specified to `generate-vcf` has been added. 
2. The plink support exposes a lot of internal classes that are not part of the release and breaks building Python/R bindings to GenomicsDB that are external to the project. Moved the support out of genomicsdb into its own header and implementation files - see genomicsdb_plink.h and genomicsdb_plink.cc. 
3. Did some refactoring and cleanup of the code, but  internal dependencies from plink need to be removed to allow for Python/R bindings. Also, the c unit test `test_bgen.cc` may need to be rewritten to use goodies from …

Remove  reference_genome parameter from GenomicsDB constructor and refactor to move plink support to its own .h/.cc files

---

.github/workflows/release.yml
src/main/cpp/include/api/genomicsdb.h
src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/api/genomicsdb_plink.cc

I need these changed to get the compiler to explicitly instantiate the relevant templates otherwise the call to `get_genomic_fields_for` from `genomicsdb_plink.cc` doesn't find the definition.
Release pipeline is still building...but hopefully this change is otherwise kosher...

Minor release fixes

---

.github/workflows/basic.yml
.github/workflows/release.yml
.github/workflows/release_test.yml
src/main/cpp/include/api/genomicsdb.h
src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/api/genomicsdb_plink.cc
src/test/cpp/CMakeLists.txt
src/test/cpp/src/test_bgen.cc

Exclude test_bgen for now if `BUILD_DISTRIBUTABLE_LIBARY` or `BUILD_FOR_PYTHON` is true as mpi is not included for these builds and test_bgen fails.
Note: This is only a temporary fix for now. See Issue #216

Exclude test_bgen for now if BUILD_DISTRIBUTABLE_LIBARY is true as mpi is not included for these builds and test_bgen fails

---

src/main/cpp/include/config/genomicsdb_config_base.h
src/main/cpp/src/config/genomicsdb_config_base.cc
src/main/cpp/src/config/json_config.cc
src/main/cpp/src/config/pb_config.cc
src/main/cpp/src/genomicsdb/genomicsdb_iterators.cc
src/resources/genomicsdb_export_config.proto
src/test/cpp/src/test_config.cc
tests/test_tools.sh

Rationale behind this bypass mechanism is as follows (thanks @mlathara) -
- in most (all?) cohort queries by genes, there is usually some padding in the regions for the gene and that should suffice to return all the sites that are relevant. this is especially true for omics data from clinical testing
- for specific mutations, missing the indels for the variant is fine, because by definition, that's not meeting the query criteria
- for sample sizes that are super large, a cohort search being a bit of a fuzzy match is OK as long as the downstream processing is aware that this is a fast, fuzzy query and they can always resort to the two pass iterator if all the results are desired.

First pass at implementing a bypass mechanism for intersecting intervals mode for fast, fuzzy queries based on just simple traversal

---

.github/workflows/codeql.yml
.github/workflows/release.yml
scripts/prereqs/install_prereqs.sh

We need to stay with ubuntu 20.04 for now as 22.04 has moved to using OpenSSL 3 by default for Github workflows. Also, removed caches for release workflows as we want to build everything from scratch and cleaned up use of `BUILD_DISTRIBUTABLE_LIBRARY` in release.yml.

Use ubuntu 20.04 explicitly for GitHub Actions and other release specific cleanup

---

.github/workflows/release_test.yml

These are failing for the current master because changes made [here](https://github.com/GenomicsDB/GenomicsDB/pull/238) also need to be pulled into GATK. 
We'll need to think about how to handle cases like this, where we potentially change something which requires a corresponding change in GATK...maybe the tag message could include something like skip_ci, and we key off that to skip the GATK IT. In fact, that seems simple enough that maybe I should make that change here? Thoughts?

Disable gatk IT for release pipeline

---

src/main/CMakeLists.txt
src/main/cpp/include/api/genomicsdb.h
src/main/cpp/include/api/genomicsdb_utils.h
src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/api/genomicsdb_utils.cc
src/test/cpp/src/test_genomicsdb_api.cc

Introduced a `genomicsdb_utils api` for accessing TileDB filesystem functionality from other languages. Only functions needed by `GDBPythonAPI` are wrapped for now to replace `fsspec`.
1. Introduced a `genomicsdb` namespace to define utility functions and to avoid clashes with other similarly named functions.
2. Deprecated `genomicsdb_version` and moved the `version()` functionality to the `genomicsdb` namespace.
3. Tried to document the new api Javadoc style for use with doxygen. We should eventually move `genomicsdb.h` to follow this style so `genomicsdb.readthedocs.io` looks cleaner for C/C++.

Expose some of the TileDB filesystem functionality in GenomicsDB for use in Python/R and probably Java bindings

---

example/java/TestGenomicsDB.java
example/java/TestGenomicsDBSource.java
example/java/TestGenomicsDBSparkHDFS.java
pom.xml
src/main/cpp/include/api/genomicsdb_status.h
src/main/cpp/include/api/genomicsdb_utils.h
src/main/cpp/include/config/genomicsdb_config_base.h
src/main/cpp/include/loader/tiledb_loader_file_base.h
src/main/cpp/src/config/genomicsdb_config_base.cc
src/main/cpp/src/config/json_config.cc
src/main/cpp/src/config/pb_config.cc
src/main/cpp/src/genomicsdb/variant_storage_manager.cc
src/main/cpp/src/loader/tiledb_loader_file_base.cc
src/main/cpp/src/utils/vid_mapper_pb.cc
src/main/java/org/genomicsdb/importer/GenomicsDBImporter.java
src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java
src/main/java/org/genomicsdb/importer/extensions/JsonFileExtensions.java
src/main/java/org/genomicsdb/reader/GenomicsDBFeatureReader.java
src/main/java/org/genomicsdb/spark/GenomicsDBSchemaFactory.java
src/main/java/org/genomicsdb/spark/api/GenomicsDBSparkBindings.java
src/resources/genomicsdb_export_config.proto
src/resources/genomicsdb_import_config.proto
src/test/java/org/genomicsdb/importer/GenomicsDBImporterSpec.java
tests/test_tools.sh
tools/src/vcf2genomicsdb.cc

Protobuf cleanup to allow for bindings from other languages to pass import/export via prototype buffers rather than plain json files. As part of this change -
1. Move to using `com.google.protobuf.util.JsonFormat` that is version matched with  `com.google.protobuf.java` rather than `com.googlecode.format.JsonFormat`.
2. Moved some defaults to the `GenomicsDBImport` constructor to allow reads from JSON and protobuf be interchangeable.
3. Extend import protobuf definitions to support `produce_combined_vcf`.
4. Removed `USE_PROTOBUF_V_3_0_0_BETA_1` ifdefs as we no longer use or support those versions.
5. Since reading to and from protobuf bypasses the [int64 issue,](https://github.com/protocolbuffers/protobuf/issues/2679)  import/export config files are parsed as protobuf's first and only on …

Protobuf cleanup to allow for import/export from other languages via prototype buffers

---

src/main/cpp/include/config/genomicsdb_config_base.h
src/main/cpp/include/loader/tiledb_loader.h
src/main/cpp/include/loader/tiledb_loader_file_base.h
src/main/cpp/src/config/pb_config.cc
src/main/cpp/src/genomicsdb/query_variants.cc
src/main/cpp/src/loader/tiledb_loader.cc
src/main/cpp/src/loader/tiledb_loader_file_base.cc
src/main/cpp/src/utils/vid_mapper.cc
tests/test_tools.sh
tools/src/vcf2genomicsdb.cc

If the `size_per_column_partition` specified via protobuf/loader.json to vcf2genomicsdb is too small, the tool was logging an error and aborting. The tiledb loader now throws a `SizePerColumnPartitionTooSmallException` when the buffer based on `size_per_column_partition` is not sufficient. It would have been ideal to resize and continue, but this buffer is split among the samples that are getting ingested and it is not easy to resize without re-architecting in a major way. For now, we are just catching the exception in `vcf2genomicsdb` and adaptively setting `size_per_column_partition` for a total of 10 tries. Each try uses a `10-index` multiplier to the existing size before aborting.
Note that `OpenMP` does not allow for exceptions to propagate as they are thrown on different threads. …

Allow for resize/retry if size_per_column_partition specified to vcf2genomicsdb is too small

---

.github/workflows/docker.yml

Update base image to resolve some CVEs. I had it pinned to a specific docker base image but...I think it is best to just take the latest image for the base OS.

Update base docker image

---

docs/building-installing.rst

Changed cmake command argument from -DCMAKE_PREFIX_INSTALL to -DCMAKE_INSTALL_PREFIX. Latter is the correct usage.

cmake argument fix for readthedocs

---

.github/workflows/basic.yml
scripts/prereqs/system/install_macos_prereqs.sh

After pulling in PR #277, noticed that codecov had stopped covering C++ sources. I could get it working again in a convoluted way. But, given  the fragility of `codecov/codecov-action@v3`  for C++/gcov, have resorted to generating the coverage info manually using `lcov` before uploading the coverage to `CodeCov`.
@mlathara, there is a lot of [spark-related code not covered](https://app.codecov.io/gh/GenomicsDB/GenomicsDB/tree/ng_codecov_0323/src/main/java/org/genomicsdb) by the tests. Is the code being used from other downstream code? What are they?

Explicit Coverage Step for C++ sources as codecov/codecov-action@v3 not handling it well

---

.github/workflows/release.yml
.github/workflows/release_jar.yml
.github/workflows/release_publish.yml
.github/workflows/release_test.yml
CMakeLists.txt
pom.xml
src/main/java/org/genomicsdb/spark/api/GenomicsDBSparkBindings.java
tests/common.py
tests/run_spark_hdfs.py

Excludes spark files by executing maven-jar plugin once more to create a jar without spark. After maven-shade creates uber jar, replacing the excluded one with regular jar.

Exclude spark from core jar

---

Dockerfile

`install_prereqs.sh` had changed in how it accepted parameters. As a result, the invocation in the dockerfile wasn't correctly passing in that we only needed release prereqs for the final image, and the resulting image was quite a bit larger than necessary (1.7G vs 330MB)

Minimize image size

---

.github/scripts/install_spark.sh
.github/workflows/basic.yml
CMakeLists.txt
example/java/TestGenomicsDBSparkHDFS.java
pom.xml
src/main/java/org/genomicsdb/spark/GenomicsDBJavaSparkFactory.java
src/main/java/org/genomicsdb/spark/api/GenomicsDBSparkBindings.java

Upgrades spark version to 3.4.0. (ToDo?) Maybe we can also remove java 11 support from workflows and move to java 17 altogether since hdfs tests are now running on java 17 anyways.

upgrade spark version to 3.4.0

---

.github/scripts/install_hadoop.sh
CMakeLists.txt
src/main/CMakeLists.txt

Install genomicsdb_status.h as this is used in the Python/R bindings.
Also, updated snapshot default version and copyrights.
Added some minor debugging echo statements to install_hadoop.sh as it was failing in the download phase initially, seems to have resolved itself.

Install genomicsdb_status.h, update snapshot version and copyrights

---

README.md
Style.md
docs/examples/gatk.rst
docs/import-etl.rst

-  Fix typos, formatting and links in import-etl docs
- Update README.md to point to genomicsdb.readthedocs.io, add badges and cleanup
- Move Styling from README to Style.md

Fix typos, formatting and links in import-etl docs and update README.md

---

scripts/prereqs/system/install_ubuntu_prereqs.sh
src/test/cpp/CMakeLists.txt
tests/test_tools.sh
tools/CMakeLists.txt
tools/src/vcf2genomicsdb.cc

`vcf2genomicsdb_init` and `vcf2genomicsdb` are built and tested in a limited way with cmake option `DISABLE_MPI` set.

Remove mpi dependencies from vcf2genomicsdb

---

pom.xml
scripts/prereqs/system/install_macos_prereqs.sh
src/main/cpp/src/genomicsdb/genomicsdb_iterators.cc
src/main/java/org/genomicsdb/importer/extensions/VidMapExtensions.java
src/main/java/org/genomicsdb/reader/GenomicsDBQuery.java
src/main/java/org/genomicsdb/spark/GenomicsDBInput.java
src/main/java/org/genomicsdb/spark/GenomicsDBInputFormat.java
src/main/java/org/genomicsdb/spark/GenomicsDBJavaSparkFactory.java
src/main/java/org/genomicsdb/spark/api/GenomicsDBQueryInputFormat.java
src/main/java/org/genomicsdb/spark/api/GenomicsDBSparkBindings.java
src/main/java/org/genomicsdb/spark/sources/GenomicsDBBatch.java
src/test/java/org/genomicsdb/GenomicsDBUtilsTest.java
src/test/java/org/genomicsdb/importer/GenomicsDBImporterSpec.java
src/test/java/org/genomicsdb/model/ImportConfigSpec.java
src/test/java/org/genomicsdb/reader/GenomicsDBQueryTest.java
src/test/java/org/genomicsdb/spark/GenomicsDBInputFormatTest.java
src/test/java/org/genomicsdb/spark/GenomicsDBQueryInputFormatTest.java

- Remove incompatible log4j between surefire plugins and the one GenomicsDB uses. 
- Cleaned up and suppressed unchecked and deprecation warnings, to figure out real mvn issues more easily.
- `brew install lcov` installs the new 2.0 which breaks a lot of our code. Need to wait for this 2.x version to be hardened a little before we fix the errors with changes in our source code and/or invoke `lcov` with additional `--ignore-errors` arguments. The scripts for macOS now explicitly install version `1.16` for non-breaking macOS builds.

Remove incompatible log4j in pom.xml and surefire causing build issues and cleanup mvn warnings

---

.github/scripts/test_hdfs_htslib_support.sh
src/main/cpp/src/vcf/htslib_fs_adapter.cc
tests/test_hfile_plugin.sh
tests/test_tools.sh
tools/include/common.h
tools/src/consolidate_genomicsdb_array.cc
tools/src/create_genomicsdb_workspace.cc
tools/src/vcf2genomicsdb.cc
tools/src/vcf2genomicsdb_init.cc

[Techincal Debt] to help diagnose issues earlier in our pipelines. Refactored a little to move common code from other tools to `common.h` and are logging all tiledb related error message as much as we can. In the process, had to modify the parsing to accommodate `azb://` URIs in `vcf2genomicsdb_init`. This parsing is already in the TileDB layer and both `TileDBUtils::get_dirs()` and `TileDBUtils::get_files()` should return URIs. See https://github.com/datma-health/TileDB/issues/159. Also, see related issue - https://github.com/datma-health/TileDB/issues/158.

Refactor create_genomicsdb_workspace to handle error messages and fit the pattern of the other tools

---

.github/workflows/release.yml
CMakeLists.txt

Last changes before starting 1.5.2 release.

Move minimal support for MacOS to version 12 and set cmake visibility setting to honor the target types.

---

.github/workflows/basic.yml
src/main/cpp/include/api/genomicsdb.h
src/main/cpp/src/api/genomicsdb.cc
src/main/jni/src/genomicsdb_GenomicsDBQuery.cc
src/main/jni/src/genomicsdb_GenomicsDBUtils.cc
src/test/cpp/src/test_genomicsdb_api.cc

Removed the already deprecated `genomicsdb_version()` from the api, we now rely only on genomicsdb::version().
Also, restricted testing of spark-hdfs to ubuntu 22.04 in GitHub workflows.

Use genomicsdb::version instead of deprecated genomicsdb_version()

---

src/main/CMakeLists.txt
src/main/cpp/include/api/genomicsdb.h
src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/api/genomicsdb_json_processor.cc
src/test/cpp/src/test_genomicsdb_api.cc

Implemented a JSON processor in the native GenomicsDB layer to generate JSON files for queries emanating from REST interfaces. 4 modes are currently supported, 
1. `all` gets all the information for the attributes queried in addition to resolving GT w.r.t REF and ALT
```{"HG00141":{"CHR":["1","1"],"POS":[12141,17385],"DP":[null,null],"GT":["C/C","G/A"]},"HG01530":{"CHR":["1"],"POS":[17385],"DP":[76],"GT":["G/A"]},"HG01958":{"CHR":["1","1"],"POS":[12145,17385],"DP":[null,120],"GT":["C/C","T/T"]}}```
2. `all_by_calls` get all the information like (1), but orders them by calls per sample
```{"FIELD":["CHR","POS","DP","GT"],"HG00141":[["1",12141,null,"C/C"],["1",17385,null,"G/A"]],"HG01530":[["1",17385,76,"G/A"]],"HG01958":[["1",12145,null,"C/C"],["1",17385,120,"T/T"]]}```
3. …

Support JSON output from genomicsdb api query_variant_calls()

---

src/test/java/org/genomicsdb/reader/GenomicsDBQueryTest.java

OpenJDK 17 seems to want explicit type match for Assert.assertEquals

---

src/main/cpp/include/api/genomicsdb.h
src/main/cpp/src/api/genomicsdb_json_processor.cc
src/test/cpp/src/test_genomicsdb_api.cc

The corresponding python test yielded this against our demo genomicsdb workspace :
```
test/test_genomicsdb_demo.py::TestGenomicsDBDemo::test_genomicsdb_demo_with_json_output test_genomicsdb_demo_with_json_output
Summary for mode=json_output_mode.NUM_CALLS:
output json length=19
Elapsed time: 2.9342398643493652
Summary for mode=json_output_mode.SAMPLES:
output json length=518592
Elapsed time: 2.978851795196533
Summary for mode=json_output_mode.SAMPLES_WITH_NUM_CALLS:
output json length=605884
Elapsed time: 3.0043089389801025
Summary for mode=json_output_mode.ALL_BY_CALLS:
output json length=2344617
Elapsed time: 3.001533269882202
Summary for mode=json_output_mode.ALL:
output json length=3558514
Elapsed time: 3.014052152633667
```

Support a samples list for json output in api queries

---

.github/workflows/docker.yml

Minor -- lunar is outside of support now so updating the 24.04 which is LTS.

Bump to ubuntu 24.05

---

.github/workflows/docker.yml
Dockerfile

I'm not entirely sure why (maybe because noble isn't officially released and some things are in flux?) but the change to noble seems to double the docker image we're building. Reverting back to jammy since that will be supported till 2027.
Also, removing a few executables that we mostly don't use from the final image

Revert to jammy due to size issues

---

src/main/cpp/include/genomicsdb/query_variants.h
src/main/cpp/include/utils/memory_measure.h
src/main/cpp/src/api/genomicsdb.cc
src/main/cpp/src/genomicsdb/variant_storage_manager.cc
src/main/cpp/src/utils/memory_measure.cc
src/test/cpp/CMakeLists.txt
src/test/cpp/src/test_genomicsdb_demo.cc
src/test/cpp/src/test_mem_utils.cc
src/test/inputs/valgrind.supp

The genomicsdb arrays are initialized as part of `VariantQueryProcessor`, but finalized only during the destruction of `VariantStorageManager`.  We now release the memory associated with genomicsdb array for every query while destroying `VariantQueryProcessor`, allowing for memory usage to be better constrained with multiple queries using the same GenomicsDB instance.

Release memory associated with genomicsdb array from VariantQueryProcessor destructor

---

src/main/cpp/src/query_operations/broad_combined_gvcf.cc

Typo from PR #332. It was only an additional check, so hopefully does not affect anything.

Fix typo associated with error checking from #332

---

src/main/cpp/src/api/genomicsdb_nanoarrow_processor.cc
src/test/cpp/src/test_genomicsdb_api.cc

Fix - when there is no value found for a genomic field given a sample/position, the loop exits prematurely when there's a previously encountered NULL for another field for the same sample/position.

Bug fix for arrow array fields that are NULLs

---

.github/workflows/basic.yml
src/main/java/org/genomicsdb/reader/GenomicsDBFeatureIterator.java
tests/golden_outputs/java_empty_vcf
tests/run.py

Instead of exceptions, log a warning when a query interval is not found in the GenomicsDB workspace(happens when the interval was not imported in the first place). Also, changed the message from a cryptic `There are no sources based on those query parameters` to something more explicit e.g. `GenomicsDB workspace does not have sources for input query interval : 2:1-300`.  See https://github.com/broadinstitute/gatk/issues/8415.
Moved to `codecov-action@v4` because v3 was erroring out for `MacOS`. v4 requires explicit codecov tokens even for open-source whereas the v3 did not.

Log warning when query intervals are not found in the workspace instead of throwing exceptions

---

.github/workflows/basic.yml
.github/workflows/codeql.yml
.github/workflows/docker.yml
.github/workflows/release.yml
.github/workflows/release_jar.yml
.github/workflows/release_publish.yml
.github/workflows/release_test.yml
CMakeLists.txt
pom.xml

See https://github.com/GenomicsDB/GenomicsDB/pull/340. We are not ready to move to protobuf 4 as yet, but `3.25.5"` has the security patches.

Move to protobuf 3.25.5 and update GitHub action versions for vulnerability fixes
